filebeat.inputs:
- type: log
  paths:
    - "/usr/share/filebeat/logs/vtex_middleware.log"
  fields_under_root: true
  json.keys_under_root: true

  processors:
  - drop_event:
      when:
        contains:
           loglevel: "DEBUG"

output.elasticsearch:
  hosts: 'elasticsearch_elk:9200'
