version: '3'

services:
 
  # Elastic Search
  elasticsearch:
    image: elasticsearch:7.3.0
    container_name: elasticsearch_elk
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      discovery.type: single-node
      cluster.name: docker-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  # Kibana
  kibana:
    image: kibana:7.3.0
    container_name: kibana_elk
    ports:
      - "5601:5601"
    restart: always
    depends_on:
      - elasticsearch

  #Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:7.3.2
    container_name: logstash_elk
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - "./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro"
      - "./logstash/pipeline/twitter.conf:/usr/share/logstash/pipeline/twitter.conf:ro"
    #  - "./logstash/sample/testdata.log:/home/logstash/testdata.log"

  # Filebeat
  #filebeat:
  #  image: docker.elastic.co/beats/filebeat:7.3.0
  #  container_name: filebeat_elk
  #  entrypoint: "filebeat -e -strict.perms=false"    
  #  restart: always
  #  depends_on:
  #    - elasticsearch
  #  volumes:
  #    - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
  #    - "/Users/douglasdossantos/work/iris-middleware-vtex/log/:/usr/share/filebeat/logs/"

  # FluentD
  #fluentd:
  #  build: ./fluentd
  #  container_name: fluentd_elk
  #  ports:
  #    - "24224:24224"
  #    - 24224:24224/udp
  #  restart: always
  #  depends_on:
  #    - elasticsearch
  #  volumes:
  #    - ./fluentd/conf:/fluentd/etc
